server:
  port: 8080

spring:
  application:
    name: colorful-logging-demo

logging:
  level:
    com.example.colorfullogging: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
